name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.29

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run tests in a Docker container to ensure correct absolute paths
      - name: Run tests
        run: |
          docker run --rm -v $(pwd):/home/bun/bun-stimulus-plugin -w /home/bun/bun-stimulus-plugin oven/bun:1.0 sh -c "bun install --frozen-lockfile && bun test"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.29

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bun run lint
